name: Java CI

on:
  push:
    branches: ["main", "refactor/project-structure"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Build with Maven
        run: mvn -B compile
      - name: Create dummy .env file for tests
        run: |
          echo "DUMMY_KEY=DUMMY_VALUE" > .env
      - name: Run tests with Maven
        run: mvn -B test
